version=${project.version}

hedgehog.version=${hedgehog.version}
hedgehog.sha256.linux=${hedgehog.sha256.linux}
hedgehog.sha256.macos=${hedgehog.sha256.macos}
hedgehog.sha256.windows=${hedgehog.sha256.windows}
