name: Janus build status

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: buildjet-8vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build config jar
      working-directory: config
      run: mvn install

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Build main
      run: xvfb-run mvn install