name: Janus build status

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        # cd into config and run mvn install
    - name: Build config jar
      working-directory: config
      run: mvn install

    - name: Build main
      run: mvn install

    - name: Slack Notifier
      # You may pin to the exact commit or the version.
      # uses: gymshark/slack-notifier-action@7c2456b691f55a62fbc7509399e37b92470a76e3
      uses: gymshark/slack-notifier-action@v1.0.2
      with:
        # webhook url
        webhook_url: https://hooks.slack.com/services/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