name: Janus build status

on:
  #push:
    #branches: [ "*" ]

  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build main
      run: mvn install

  browser:

    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build main without tests
      run: mvn -B install -DskipTests

    - name: Install Chromium for Playwright
      run: >-
        mvn -B -Pbrowser -pl e2e exec:java -Dexec.mainClass=com.microsoft.playwright.CLI
        -Dexec.classpathScope=test -Dexec.args="install --with-deps chromium"

    - name: Run browser tests
      run: mvn -B -Pbrowser -pl e2e verify
