name: 'Close Stale Issues'

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Mark and close stale issues
      uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.'
        days-before-stale: 30 # Mark issues as stale after 30 days of inactivity
        days-before-close: 7 # Close stale issues after 7 days of being marked as stale
        stale-issue-label: 'stale'
        close-issue-message: 'This issue has been closed due to inactivity.'

